/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppInventoryRouteImport } from './routes/_app/_inventory'
import { Route as AppMasterRouteImport } from './routes/_app/_master'
import { Route as AppPriceRouteImport } from './routes/_app/_price'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AppInventoryReceiptsRouteImport } from './routes/_app/_inventory/receipts'
import { Route as AppMasterCategoriesRouteImport } from './routes/_app/_master/categories'
import { Route as AppMasterItemsRouteImport } from './routes/_app/_master/items'
import { Route as AppMasterLocationsRouteImport } from './routes/_app/_master/locations'
import { Route as AppLicenseIndexRouteImport } from './routes/_app/license/index'
import { Route as AppInventoryInventoryIndexRouteImport } from './routes/_app/_inventory/inventory/index'
import { Route as AppInventoryInventoryItemsRouteImport } from './routes/_app/_inventory/inventory/items'
import { Route as AppInventoryReceiptsIndexRouteImport } from './routes/_app/_inventory/receipts/index'
import { Route as AppMasterCategoriesIndexRouteImport } from './routes/_app/_master/categories/index'
import { Route as AppMasterCategoriesSplatRouteImport } from './routes/_app/_master/categories/$'
import { Route as AppMasterItemsIndexRouteImport } from './routes/_app/_master/items/index'
import { Route as AppMasterLocationsIndexRouteImport } from './routes/_app/_master/locations/index'
import { Route as AppMasterLocationsSplatRouteImport } from './routes/_app/_master/locations/$'
import { Route as AppMasterProvidersIndexRouteImport } from './routes/_app/_master/providers/index'
import { Route as AppMasterReferencesIndexRouteImport } from './routes/_app/_master/references/index'
import { Route as AppPricePricesIndexRouteImport } from './routes/_app/_price/prices/index'
import { Route as AppPriceStoresIndexRouteImport } from './routes/_app/_price/stores/index'
import { Route as AppSettingsIntegrationsIndexRouteImport } from './routes/_app/settings/integrations/index'
import { Route as AppSettingsMcpIndexRouteImport } from './routes/_app/settings/mcp/index'
import { Route as AppInventoryInventoryHistoryIndexRouteImport } from './routes/_app/_inventory/inventory/history/index'
import { Route as AppInventoryInventoryIssueIndexRouteImport } from './routes/_app/_inventory/inventory/issue/index'
import { Route as AppInventoryInventoryItemsIndexRouteImport } from './routes/_app/_inventory/inventory/items/index'
import { Route as AppInventoryInventoryReceiveIndexRouteImport } from './routes/_app/_inventory/inventory/receive/index'
import { Route as AppInventoryInventoryStocktakeIndexRouteImport } from './routes/_app/_inventory/inventory/stocktake/index'
import { Route as AppInventoryReceiptsReceiptIdIndexRouteImport } from './routes/_app/_inventory/receipts/$receiptId/index'
import { Route as AppInventoryReceiptsNewIndexRouteImport } from './routes/_app/_inventory/receipts/new/index'
import { Route as AppMasterItemsItemIdIndexRouteImport } from './routes/_app/_master/items/$itemId/index'
import { Route as AppInventoryInventoryItemsItemIdIndexRouteImport } from './routes/_app/_inventory/inventory/items/$itemId/index'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/_inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterRoute = AppMasterRouteImport.update({
  id: '/_master',
  getParentRoute: () => AppRoute,
} as any)
const AppPriceRoute = AppPriceRouteImport.update({
  id: '/_price',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInventoryReceiptsRoute = AppInventoryReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppMasterCategoriesRoute = AppMasterCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppMasterRoute,
} as any)
const AppMasterItemsRoute = AppMasterItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AppMasterRoute,
} as any)
const AppMasterLocationsRoute = AppMasterLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppMasterRoute,
} as any)
const AppLicenseIndexRoute = AppLicenseIndexRouteImport.update({
  id: '/license/',
  path: '/license/',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryInventoryIndexRoute =
  AppInventoryInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AppInventoryRoute,
  } as any)
const AppInventoryInventoryItemsRoute =
  AppInventoryInventoryItemsRouteImport.update({
    id: '/inventory/items',
    path: '/inventory/items',
    getParentRoute: () => AppInventoryRoute,
  } as any)
const AppInventoryReceiptsIndexRoute =
  AppInventoryReceiptsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppInventoryReceiptsRoute,
  } as any)
const AppMasterCategoriesIndexRoute =
  AppMasterCategoriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppMasterCategoriesRoute,
  } as any)
const AppMasterCategoriesSplatRoute =
  AppMasterCategoriesSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => AppMasterCategoriesRoute,
  } as any)
const AppMasterItemsIndexRoute = AppMasterItemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMasterItemsRoute,
} as any)
const AppMasterLocationsIndexRoute = AppMasterLocationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMasterLocationsRoute,
} as any)
const AppMasterLocationsSplatRoute = AppMasterLocationsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppMasterLocationsRoute,
} as any)
const AppMasterProvidersIndexRoute = AppMasterProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => AppMasterRoute,
} as any)
const AppMasterReferencesIndexRoute =
  AppMasterReferencesIndexRouteImport.update({
    id: '/references/',
    path: '/references/',
    getParentRoute: () => AppMasterRoute,
  } as any)
const AppPricePricesIndexRoute = AppPricePricesIndexRouteImport.update({
  id: '/prices/',
  path: '/prices/',
  getParentRoute: () => AppPriceRoute,
} as any)
const AppPriceStoresIndexRoute = AppPriceStoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => AppPriceRoute,
} as any)
const AppSettingsIntegrationsIndexRoute =
  AppSettingsIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsMcpIndexRoute = AppSettingsMcpIndexRouteImport.update({
  id: '/mcp/',
  path: '/mcp/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppInventoryInventoryHistoryIndexRoute =
  AppInventoryInventoryHistoryIndexRouteImport.update({
    id: '/inventory/history/',
    path: '/inventory/history/',
    getParentRoute: () => AppInventoryRoute,
  } as any)
const AppInventoryInventoryIssueIndexRoute =
  AppInventoryInventoryIssueIndexRouteImport.update({
    id: '/inventory/issue/',
    path: '/inventory/issue/',
    getParentRoute: () => AppInventoryRoute,
  } as any)
const AppInventoryInventoryItemsIndexRoute =
  AppInventoryInventoryItemsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppInventoryInventoryItemsRoute,
  } as any)
const AppInventoryInventoryReceiveIndexRoute =
  AppInventoryInventoryReceiveIndexRouteImport.update({
    id: '/inventory/receive/',
    path: '/inventory/receive/',
    getParentRoute: () => AppInventoryRoute,
  } as any)
const AppInventoryInventoryStocktakeIndexRoute =
  AppInventoryInventoryStocktakeIndexRouteImport.update({
    id: '/inventory/stocktake/',
    path: '/inventory/stocktake/',
    getParentRoute: () => AppInventoryRoute,
  } as any)
const AppInventoryReceiptsReceiptIdIndexRoute =
  AppInventoryReceiptsReceiptIdIndexRouteImport.update({
    id: '/$receiptId/',
    path: '/$receiptId/',
    getParentRoute: () => AppInventoryReceiptsRoute,
  } as any)
const AppInventoryReceiptsNewIndexRoute =
  AppInventoryReceiptsNewIndexRouteImport.update({
    id: '/new/',
    path: '/new/',
    getParentRoute: () => AppInventoryReceiptsRoute,
  } as any)
const AppMasterItemsItemIdIndexRoute =
  AppMasterItemsItemIdIndexRouteImport.update({
    id: '/$itemId/',
    path: '/$itemId/',
    getParentRoute: () => AppMasterItemsRoute,
  } as any)
const AppInventoryInventoryItemsItemIdIndexRoute =
  AppInventoryInventoryItemsItemIdIndexRouteImport.update({
    id: '/$itemId/',
    path: '/$itemId/',
    getParentRoute: () => AppInventoryInventoryItemsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/receipts': typeof AppInventoryReceiptsRouteWithChildren
  '/categories': typeof AppMasterCategoriesRouteWithChildren
  '/items': typeof AppMasterItemsRouteWithChildren
  '/locations': typeof AppMasterLocationsRouteWithChildren
  '/license/': typeof AppLicenseIndexRoute
  '/inventory/items': typeof AppInventoryInventoryItemsRouteWithChildren
  '/categories/$': typeof AppMasterCategoriesSplatRoute
  '/locations/$': typeof AppMasterLocationsSplatRoute
  '/inventory/': typeof AppInventoryInventoryIndexRoute
  '/receipts/': typeof AppInventoryReceiptsIndexRoute
  '/categories/': typeof AppMasterCategoriesIndexRoute
  '/items/': typeof AppMasterItemsIndexRoute
  '/locations/': typeof AppMasterLocationsIndexRoute
  '/providers/': typeof AppMasterProvidersIndexRoute
  '/references/': typeof AppMasterReferencesIndexRoute
  '/prices/': typeof AppPricePricesIndexRoute
  '/stores/': typeof AppPriceStoresIndexRoute
  '/settings/integrations/': typeof AppSettingsIntegrationsIndexRoute
  '/settings/mcp/': typeof AppSettingsMcpIndexRoute
  '/inventory/history/': typeof AppInventoryInventoryHistoryIndexRoute
  '/inventory/issue/': typeof AppInventoryInventoryIssueIndexRoute
  '/inventory/items/': typeof AppInventoryInventoryItemsIndexRoute
  '/inventory/receive/': typeof AppInventoryInventoryReceiveIndexRoute
  '/inventory/stocktake/': typeof AppInventoryInventoryStocktakeIndexRoute
  '/receipts/$receiptId/': typeof AppInventoryReceiptsReceiptIdIndexRoute
  '/receipts/new/': typeof AppInventoryReceiptsNewIndexRoute
  '/items/$itemId/': typeof AppMasterItemsItemIdIndexRoute
  '/inventory/items/$itemId/': typeof AppInventoryInventoryItemsItemIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/license': typeof AppLicenseIndexRoute
  '/categories/$': typeof AppMasterCategoriesSplatRoute
  '/locations/$': typeof AppMasterLocationsSplatRoute
  '/inventory': typeof AppInventoryInventoryIndexRoute
  '/receipts': typeof AppInventoryReceiptsIndexRoute
  '/categories': typeof AppMasterCategoriesIndexRoute
  '/items': typeof AppMasterItemsIndexRoute
  '/locations': typeof AppMasterLocationsIndexRoute
  '/providers': typeof AppMasterProvidersIndexRoute
  '/references': typeof AppMasterReferencesIndexRoute
  '/prices': typeof AppPricePricesIndexRoute
  '/stores': typeof AppPriceStoresIndexRoute
  '/settings/integrations': typeof AppSettingsIntegrationsIndexRoute
  '/settings/mcp': typeof AppSettingsMcpIndexRoute
  '/inventory/history': typeof AppInventoryInventoryHistoryIndexRoute
  '/inventory/issue': typeof AppInventoryInventoryIssueIndexRoute
  '/inventory/items': typeof AppInventoryInventoryItemsIndexRoute
  '/inventory/receive': typeof AppInventoryInventoryReceiveIndexRoute
  '/inventory/stocktake': typeof AppInventoryInventoryStocktakeIndexRoute
  '/receipts/$receiptId': typeof AppInventoryReceiptsReceiptIdIndexRoute
  '/receipts/new': typeof AppInventoryReceiptsNewIndexRoute
  '/items/$itemId': typeof AppMasterItemsItemIdIndexRoute
  '/inventory/items/$itemId': typeof AppInventoryInventoryItemsItemIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/_inventory': typeof AppInventoryRouteWithChildren
  '/_app/_master': typeof AppMasterRouteWithChildren
  '/_app/_price': typeof AppPriceRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_inventory/receipts': typeof AppInventoryReceiptsRouteWithChildren
  '/_app/_master/categories': typeof AppMasterCategoriesRouteWithChildren
  '/_app/_master/items': typeof AppMasterItemsRouteWithChildren
  '/_app/_master/locations': typeof AppMasterLocationsRouteWithChildren
  '/_app/license/': typeof AppLicenseIndexRoute
  '/_app/_inventory/inventory/items': typeof AppInventoryInventoryItemsRouteWithChildren
  '/_app/_master/categories/$': typeof AppMasterCategoriesSplatRoute
  '/_app/_master/locations/$': typeof AppMasterLocationsSplatRoute
  '/_app/_inventory/inventory/': typeof AppInventoryInventoryIndexRoute
  '/_app/_inventory/receipts/': typeof AppInventoryReceiptsIndexRoute
  '/_app/_master/categories/': typeof AppMasterCategoriesIndexRoute
  '/_app/_master/items/': typeof AppMasterItemsIndexRoute
  '/_app/_master/locations/': typeof AppMasterLocationsIndexRoute
  '/_app/_master/providers/': typeof AppMasterProvidersIndexRoute
  '/_app/_master/references/': typeof AppMasterReferencesIndexRoute
  '/_app/_price/prices/': typeof AppPricePricesIndexRoute
  '/_app/_price/stores/': typeof AppPriceStoresIndexRoute
  '/_app/settings/integrations/': typeof AppSettingsIntegrationsIndexRoute
  '/_app/settings/mcp/': typeof AppSettingsMcpIndexRoute
  '/_app/_inventory/inventory/history/': typeof AppInventoryInventoryHistoryIndexRoute
  '/_app/_inventory/inventory/issue/': typeof AppInventoryInventoryIssueIndexRoute
  '/_app/_inventory/inventory/items/': typeof AppInventoryInventoryItemsIndexRoute
  '/_app/_inventory/inventory/receive/': typeof AppInventoryInventoryReceiveIndexRoute
  '/_app/_inventory/inventory/stocktake/': typeof AppInventoryInventoryStocktakeIndexRoute
  '/_app/_inventory/receipts/$receiptId/': typeof AppInventoryReceiptsReceiptIdIndexRoute
  '/_app/_inventory/receipts/new/': typeof AppInventoryReceiptsNewIndexRoute
  '/_app/_master/items/$itemId/': typeof AppMasterItemsItemIdIndexRoute
  '/_app/_inventory/inventory/items/$itemId/': typeof AppInventoryInventoryItemsItemIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/api/$'
    | '/receipts'
    | '/categories'
    | '/items'
    | '/locations'
    | '/license/'
    | '/inventory/items'
    | '/categories/$'
    | '/locations/$'
    | '/inventory/'
    | '/receipts/'
    | '/categories/'
    | '/items/'
    | '/locations/'
    | '/providers/'
    | '/references/'
    | '/prices/'
    | '/stores/'
    | '/settings/integrations/'
    | '/settings/mcp/'
    | '/inventory/history/'
    | '/inventory/issue/'
    | '/inventory/items/'
    | '/inventory/receive/'
    | '/inventory/stocktake/'
    | '/receipts/$receiptId/'
    | '/receipts/new/'
    | '/items/$itemId/'
    | '/inventory/items/$itemId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/api/$'
    | '/license'
    | '/categories/$'
    | '/locations/$'
    | '/inventory'
    | '/receipts'
    | '/categories'
    | '/items'
    | '/locations'
    | '/providers'
    | '/references'
    | '/prices'
    | '/stores'
    | '/settings/integrations'
    | '/settings/mcp'
    | '/inventory/history'
    | '/inventory/issue'
    | '/inventory/items'
    | '/inventory/receive'
    | '/inventory/stocktake'
    | '/receipts/$receiptId'
    | '/receipts/new'
    | '/items/$itemId'
    | '/inventory/items/$itemId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/_inventory'
    | '/_app/_master'
    | '/_app/_price'
    | '/_app/settings'
    | '/api/$'
    | '/_app/'
    | '/_app/_inventory/receipts'
    | '/_app/_master/categories'
    | '/_app/_master/items'
    | '/_app/_master/locations'
    | '/_app/license/'
    | '/_app/_inventory/inventory/items'
    | '/_app/_master/categories/$'
    | '/_app/_master/locations/$'
    | '/_app/_inventory/inventory/'
    | '/_app/_inventory/receipts/'
    | '/_app/_master/categories/'
    | '/_app/_master/items/'
    | '/_app/_master/locations/'
    | '/_app/_master/providers/'
    | '/_app/_master/references/'
    | '/_app/_price/prices/'
    | '/_app/_price/stores/'
    | '/_app/settings/integrations/'
    | '/_app/settings/mcp/'
    | '/_app/_inventory/inventory/history/'
    | '/_app/_inventory/inventory/issue/'
    | '/_app/_inventory/inventory/items/'
    | '/_app/_inventory/inventory/receive/'
    | '/_app/_inventory/inventory/stocktake/'
    | '/_app/_inventory/receipts/$receiptId/'
    | '/_app/_inventory/receipts/new/'
    | '/_app/_master/items/$itemId/'
    | '/_app/_inventory/inventory/items/$itemId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_inventory': {
      id: '/_app/_inventory'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_master': {
      id: '/_app/_master'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppMasterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_price': {
      id: '/_app/_price'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppPriceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_inventory/receipts': {
      id: '/_app/_inventory/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof AppInventoryReceiptsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/_master/categories': {
      id: '/_app/_master/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppMasterCategoriesRouteImport
      parentRoute: typeof AppMasterRoute
    }
    '/_app/_master/items': {
      id: '/_app/_master/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AppMasterItemsRouteImport
      parentRoute: typeof AppMasterRoute
    }
    '/_app/_master/locations': {
      id: '/_app/_master/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AppMasterLocationsRouteImport
      parentRoute: typeof AppMasterRoute
    }
    '/_app/license/': {
      id: '/_app/license/'
      path: '/license'
      fullPath: '/license/'
      preLoaderRoute: typeof AppLicenseIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_inventory/inventory/': {
      id: '/_app/_inventory/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryInventoryIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/_inventory/inventory/items': {
      id: '/_app/_inventory/inventory/items'
      path: '/inventory/items'
      fullPath: '/inventory/items'
      preLoaderRoute: typeof AppInventoryInventoryItemsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/_inventory/receipts/': {
      id: '/_app/_inventory/receipts/'
      path: '/'
      fullPath: '/receipts/'
      preLoaderRoute: typeof AppInventoryReceiptsIndexRouteImport
      parentRoute: typeof AppInventoryReceiptsRoute
    }
    '/_app/_master/categories/': {
      id: '/_app/_master/categories/'
      path: '/'
      fullPath: '/categories/'
      preLoaderRoute: typeof AppMasterCategoriesIndexRouteImport
      parentRoute: typeof AppMasterCategoriesRoute
    }
    '/_app/_master/categories/$': {
      id: '/_app/_master/categories/$'
      path: '/$'
      fullPath: '/categories/$'
      preLoaderRoute: typeof AppMasterCategoriesSplatRouteImport
      parentRoute: typeof AppMasterCategoriesRoute
    }
    '/_app/_master/items/': {
      id: '/_app/_master/items/'
      path: '/'
      fullPath: '/items/'
      preLoaderRoute: typeof AppMasterItemsIndexRouteImport
      parentRoute: typeof AppMasterItemsRoute
    }
    '/_app/_master/locations/': {
      id: '/_app/_master/locations/'
      path: '/'
      fullPath: '/locations/'
      preLoaderRoute: typeof AppMasterLocationsIndexRouteImport
      parentRoute: typeof AppMasterLocationsRoute
    }
    '/_app/_master/locations/$': {
      id: '/_app/_master/locations/$'
      path: '/$'
      fullPath: '/locations/$'
      preLoaderRoute: typeof AppMasterLocationsSplatRouteImport
      parentRoute: typeof AppMasterLocationsRoute
    }
    '/_app/_master/providers/': {
      id: '/_app/_master/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof AppMasterProvidersIndexRouteImport
      parentRoute: typeof AppMasterRoute
    }
    '/_app/_master/references/': {
      id: '/_app/_master/references/'
      path: '/references'
      fullPath: '/references/'
      preLoaderRoute: typeof AppMasterReferencesIndexRouteImport
      parentRoute: typeof AppMasterRoute
    }
    '/_app/_price/prices/': {
      id: '/_app/_price/prices/'
      path: '/prices'
      fullPath: '/prices/'
      preLoaderRoute: typeof AppPricePricesIndexRouteImport
      parentRoute: typeof AppPriceRoute
    }
    '/_app/_price/stores/': {
      id: '/_app/_price/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof AppPriceStoresIndexRouteImport
      parentRoute: typeof AppPriceRoute
    }
    '/_app/settings/integrations/': {
      id: '/_app/settings/integrations/'
      path: '/integrations'
      fullPath: '/settings/integrations/'
      preLoaderRoute: typeof AppSettingsIntegrationsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/mcp/': {
      id: '/_app/settings/mcp/'
      path: '/mcp'
      fullPath: '/settings/mcp/'
      preLoaderRoute: typeof AppSettingsMcpIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/_inventory/inventory/history/': {
      id: '/_app/_inventory/inventory/history/'
      path: '/inventory/history'
      fullPath: '/inventory/history/'
      preLoaderRoute: typeof AppInventoryInventoryHistoryIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/_inventory/inventory/issue/': {
      id: '/_app/_inventory/inventory/issue/'
      path: '/inventory/issue'
      fullPath: '/inventory/issue/'
      preLoaderRoute: typeof AppInventoryInventoryIssueIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/_inventory/inventory/items/': {
      id: '/_app/_inventory/inventory/items/'
      path: '/'
      fullPath: '/inventory/items/'
      preLoaderRoute: typeof AppInventoryInventoryItemsIndexRouteImport
      parentRoute: typeof AppInventoryInventoryItemsRoute
    }
    '/_app/_inventory/inventory/receive/': {
      id: '/_app/_inventory/inventory/receive/'
      path: '/inventory/receive'
      fullPath: '/inventory/receive/'
      preLoaderRoute: typeof AppInventoryInventoryReceiveIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/_inventory/inventory/stocktake/': {
      id: '/_app/_inventory/inventory/stocktake/'
      path: '/inventory/stocktake'
      fullPath: '/inventory/stocktake/'
      preLoaderRoute: typeof AppInventoryInventoryStocktakeIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/_inventory/receipts/$receiptId/': {
      id: '/_app/_inventory/receipts/$receiptId/'
      path: '/$receiptId'
      fullPath: '/receipts/$receiptId/'
      preLoaderRoute: typeof AppInventoryReceiptsReceiptIdIndexRouteImport
      parentRoute: typeof AppInventoryReceiptsRoute
    }
    '/_app/_inventory/receipts/new/': {
      id: '/_app/_inventory/receipts/new/'
      path: '/new'
      fullPath: '/receipts/new/'
      preLoaderRoute: typeof AppInventoryReceiptsNewIndexRouteImport
      parentRoute: typeof AppInventoryReceiptsRoute
    }
    '/_app/_master/items/$itemId/': {
      id: '/_app/_master/items/$itemId/'
      path: '/$itemId'
      fullPath: '/items/$itemId/'
      preLoaderRoute: typeof AppMasterItemsItemIdIndexRouteImport
      parentRoute: typeof AppMasterItemsRoute
    }
    '/_app/_inventory/inventory/items/$itemId/': {
      id: '/_app/_inventory/inventory/items/$itemId/'
      path: '/$itemId'
      fullPath: '/inventory/items/$itemId/'
      preLoaderRoute: typeof AppInventoryInventoryItemsItemIdIndexRouteImport
      parentRoute: typeof AppInventoryInventoryItemsRoute
    }
  }
}

interface AppInventoryReceiptsRouteChildren {
  AppInventoryReceiptsIndexRoute: typeof AppInventoryReceiptsIndexRoute
  AppInventoryReceiptsReceiptIdIndexRoute: typeof AppInventoryReceiptsReceiptIdIndexRoute
  AppInventoryReceiptsNewIndexRoute: typeof AppInventoryReceiptsNewIndexRoute
}

const AppInventoryReceiptsRouteChildren: AppInventoryReceiptsRouteChildren = {
  AppInventoryReceiptsIndexRoute: AppInventoryReceiptsIndexRoute,
  AppInventoryReceiptsReceiptIdIndexRoute:
    AppInventoryReceiptsReceiptIdIndexRoute,
  AppInventoryReceiptsNewIndexRoute: AppInventoryReceiptsNewIndexRoute,
}

const AppInventoryReceiptsRouteWithChildren =
  AppInventoryReceiptsRoute._addFileChildren(AppInventoryReceiptsRouteChildren)

interface AppInventoryInventoryItemsRouteChildren {
  AppInventoryInventoryItemsIndexRoute: typeof AppInventoryInventoryItemsIndexRoute
  AppInventoryInventoryItemsItemIdIndexRoute: typeof AppInventoryInventoryItemsItemIdIndexRoute
}

const AppInventoryInventoryItemsRouteChildren: AppInventoryInventoryItemsRouteChildren =
  {
    AppInventoryInventoryItemsIndexRoute: AppInventoryInventoryItemsIndexRoute,
    AppInventoryInventoryItemsItemIdIndexRoute:
      AppInventoryInventoryItemsItemIdIndexRoute,
  }

const AppInventoryInventoryItemsRouteWithChildren =
  AppInventoryInventoryItemsRoute._addFileChildren(
    AppInventoryInventoryItemsRouteChildren,
  )

interface AppInventoryRouteChildren {
  AppInventoryReceiptsRoute: typeof AppInventoryReceiptsRouteWithChildren
  AppInventoryInventoryItemsRoute: typeof AppInventoryInventoryItemsRouteWithChildren
  AppInventoryInventoryIndexRoute: typeof AppInventoryInventoryIndexRoute
  AppInventoryInventoryHistoryIndexRoute: typeof AppInventoryInventoryHistoryIndexRoute
  AppInventoryInventoryIssueIndexRoute: typeof AppInventoryInventoryIssueIndexRoute
  AppInventoryInventoryReceiveIndexRoute: typeof AppInventoryInventoryReceiveIndexRoute
  AppInventoryInventoryStocktakeIndexRoute: typeof AppInventoryInventoryStocktakeIndexRoute
}

const AppInventoryRouteChildren: AppInventoryRouteChildren = {
  AppInventoryReceiptsRoute: AppInventoryReceiptsRouteWithChildren,
  AppInventoryInventoryItemsRoute: AppInventoryInventoryItemsRouteWithChildren,
  AppInventoryInventoryIndexRoute: AppInventoryInventoryIndexRoute,
  AppInventoryInventoryHistoryIndexRoute:
    AppInventoryInventoryHistoryIndexRoute,
  AppInventoryInventoryIssueIndexRoute: AppInventoryInventoryIssueIndexRoute,
  AppInventoryInventoryReceiveIndexRoute:
    AppInventoryInventoryReceiveIndexRoute,
  AppInventoryInventoryStocktakeIndexRoute:
    AppInventoryInventoryStocktakeIndexRoute,
}

const AppInventoryRouteWithChildren = AppInventoryRoute._addFileChildren(
  AppInventoryRouteChildren,
)

interface AppMasterCategoriesRouteChildren {
  AppMasterCategoriesSplatRoute: typeof AppMasterCategoriesSplatRoute
  AppMasterCategoriesIndexRoute: typeof AppMasterCategoriesIndexRoute
}

const AppMasterCategoriesRouteChildren: AppMasterCategoriesRouteChildren = {
  AppMasterCategoriesSplatRoute: AppMasterCategoriesSplatRoute,
  AppMasterCategoriesIndexRoute: AppMasterCategoriesIndexRoute,
}

const AppMasterCategoriesRouteWithChildren =
  AppMasterCategoriesRoute._addFileChildren(AppMasterCategoriesRouteChildren)

interface AppMasterItemsRouteChildren {
  AppMasterItemsIndexRoute: typeof AppMasterItemsIndexRoute
  AppMasterItemsItemIdIndexRoute: typeof AppMasterItemsItemIdIndexRoute
}

const AppMasterItemsRouteChildren: AppMasterItemsRouteChildren = {
  AppMasterItemsIndexRoute: AppMasterItemsIndexRoute,
  AppMasterItemsItemIdIndexRoute: AppMasterItemsItemIdIndexRoute,
}

const AppMasterItemsRouteWithChildren = AppMasterItemsRoute._addFileChildren(
  AppMasterItemsRouteChildren,
)

interface AppMasterLocationsRouteChildren {
  AppMasterLocationsSplatRoute: typeof AppMasterLocationsSplatRoute
  AppMasterLocationsIndexRoute: typeof AppMasterLocationsIndexRoute
}

const AppMasterLocationsRouteChildren: AppMasterLocationsRouteChildren = {
  AppMasterLocationsSplatRoute: AppMasterLocationsSplatRoute,
  AppMasterLocationsIndexRoute: AppMasterLocationsIndexRoute,
}

const AppMasterLocationsRouteWithChildren =
  AppMasterLocationsRoute._addFileChildren(AppMasterLocationsRouteChildren)

interface AppMasterRouteChildren {
  AppMasterCategoriesRoute: typeof AppMasterCategoriesRouteWithChildren
  AppMasterItemsRoute: typeof AppMasterItemsRouteWithChildren
  AppMasterLocationsRoute: typeof AppMasterLocationsRouteWithChildren
  AppMasterProvidersIndexRoute: typeof AppMasterProvidersIndexRoute
  AppMasterReferencesIndexRoute: typeof AppMasterReferencesIndexRoute
}

const AppMasterRouteChildren: AppMasterRouteChildren = {
  AppMasterCategoriesRoute: AppMasterCategoriesRouteWithChildren,
  AppMasterItemsRoute: AppMasterItemsRouteWithChildren,
  AppMasterLocationsRoute: AppMasterLocationsRouteWithChildren,
  AppMasterProvidersIndexRoute: AppMasterProvidersIndexRoute,
  AppMasterReferencesIndexRoute: AppMasterReferencesIndexRoute,
}

const AppMasterRouteWithChildren = AppMasterRoute._addFileChildren(
  AppMasterRouteChildren,
)

interface AppPriceRouteChildren {
  AppPricePricesIndexRoute: typeof AppPricePricesIndexRoute
  AppPriceStoresIndexRoute: typeof AppPriceStoresIndexRoute
}

const AppPriceRouteChildren: AppPriceRouteChildren = {
  AppPricePricesIndexRoute: AppPricePricesIndexRoute,
  AppPriceStoresIndexRoute: AppPriceStoresIndexRoute,
}

const AppPriceRouteWithChildren = AppPriceRoute._addFileChildren(
  AppPriceRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsIntegrationsIndexRoute: typeof AppSettingsIntegrationsIndexRoute
  AppSettingsMcpIndexRoute: typeof AppSettingsMcpIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsIntegrationsIndexRoute: AppSettingsIntegrationsIndexRoute,
  AppSettingsMcpIndexRoute: AppSettingsMcpIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppInventoryRoute: typeof AppInventoryRouteWithChildren
  AppMasterRoute: typeof AppMasterRouteWithChildren
  AppPriceRoute: typeof AppPriceRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppLicenseIndexRoute: typeof AppLicenseIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInventoryRoute: AppInventoryRouteWithChildren,
  AppMasterRoute: AppMasterRouteWithChildren,
  AppPriceRoute: AppPriceRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppLicenseIndexRoute: AppLicenseIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
