/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppMasterRouteImport } from './routes/_app/_master'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AppInventoryIndexRouteImport } from './routes/_app/inventory/index'
import { Route as AppLicenseIndexRouteImport } from './routes/_app/license/index'
import { Route as AppMasterCategoriesIndexRouteImport } from './routes/_app/_master/categories/index'
import { Route as AppMasterItemsIndexRouteImport } from './routes/_app/_master/items/index'
import { Route as AppMasterLocationsIndexRouteImport } from './routes/_app/_master/locations/index'
import { Route as AppMasterReferencesIndexRouteImport } from './routes/_app/_master/references/index'
import { Route as AppInventoryHistoryIndexRouteImport } from './routes/_app/inventory/history/index'
import { Route as AppInventoryIssueIndexRouteImport } from './routes/_app/inventory/issue/index'
import { Route as AppInventoryReceiveIndexRouteImport } from './routes/_app/inventory/receive/index'
import { Route as AppInventoryStocktakeIndexRouteImport } from './routes/_app/inventory/stocktake/index'
import { Route as AppReceiptsNewIndexRouteImport } from './routes/_app/receipts/new/index'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterRoute = AppMasterRouteImport.update({
  id: '/_master',
  getParentRoute: () => AppRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AppRoute,
} as any)
const AppLicenseIndexRoute = AppLicenseIndexRouteImport.update({
  id: '/license/',
  path: '/license/',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterCategoriesIndexRoute =
  AppMasterCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AppMasterRoute,
  } as any)
const AppMasterItemsIndexRoute = AppMasterItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => AppMasterRoute,
} as any)
const AppMasterLocationsIndexRoute = AppMasterLocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => AppMasterRoute,
} as any)
const AppMasterReferencesIndexRoute =
  AppMasterReferencesIndexRouteImport.update({
    id: '/references/',
    path: '/references/',
    getParentRoute: () => AppMasterRoute,
  } as any)
const AppInventoryHistoryIndexRoute =
  AppInventoryHistoryIndexRouteImport.update({
    id: '/inventory/history/',
    path: '/inventory/history/',
    getParentRoute: () => AppRoute,
  } as any)
const AppInventoryIssueIndexRoute = AppInventoryIssueIndexRouteImport.update({
  id: '/inventory/issue/',
  path: '/inventory/issue/',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryReceiveIndexRoute =
  AppInventoryReceiveIndexRouteImport.update({
    id: '/inventory/receive/',
    path: '/inventory/receive/',
    getParentRoute: () => AppRoute,
  } as any)
const AppInventoryStocktakeIndexRoute =
  AppInventoryStocktakeIndexRouteImport.update({
    id: '/inventory/stocktake/',
    path: '/inventory/stocktake/',
    getParentRoute: () => AppRoute,
  } as any)
const AppReceiptsNewIndexRoute = AppReceiptsNewIndexRouteImport.update({
  id: '/receipts/new/',
  path: '/receipts/new/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/api/$': typeof ApiSplatRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/license/': typeof AppLicenseIndexRoute
  '/categories/': typeof AppMasterCategoriesIndexRoute
  '/items/': typeof AppMasterItemsIndexRoute
  '/locations/': typeof AppMasterLocationsIndexRoute
  '/references/': typeof AppMasterReferencesIndexRoute
  '/inventory/history/': typeof AppInventoryHistoryIndexRoute
  '/inventory/issue/': typeof AppInventoryIssueIndexRoute
  '/inventory/receive/': typeof AppInventoryReceiveIndexRoute
  '/inventory/stocktake/': typeof AppInventoryStocktakeIndexRoute
  '/receipts/new/': typeof AppReceiptsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/api/$': typeof ApiSplatRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/license': typeof AppLicenseIndexRoute
  '/categories': typeof AppMasterCategoriesIndexRoute
  '/items': typeof AppMasterItemsIndexRoute
  '/locations': typeof AppMasterLocationsIndexRoute
  '/references': typeof AppMasterReferencesIndexRoute
  '/inventory/history': typeof AppInventoryHistoryIndexRoute
  '/inventory/issue': typeof AppInventoryIssueIndexRoute
  '/inventory/receive': typeof AppInventoryReceiveIndexRoute
  '/inventory/stocktake': typeof AppInventoryStocktakeIndexRoute
  '/receipts/new': typeof AppReceiptsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/_master': typeof AppMasterRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/license/': typeof AppLicenseIndexRoute
  '/_app/_master/categories/': typeof AppMasterCategoriesIndexRoute
  '/_app/_master/items/': typeof AppMasterItemsIndexRoute
  '/_app/_master/locations/': typeof AppMasterLocationsIndexRoute
  '/_app/_master/references/': typeof AppMasterReferencesIndexRoute
  '/_app/inventory/history/': typeof AppInventoryHistoryIndexRoute
  '/_app/inventory/issue/': typeof AppInventoryIssueIndexRoute
  '/_app/inventory/receive/': typeof AppInventoryReceiveIndexRoute
  '/_app/inventory/stocktake/': typeof AppInventoryStocktakeIndexRoute
  '/_app/receipts/new/': typeof AppReceiptsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/$'
    | '/inventory/'
    | '/license/'
    | '/categories/'
    | '/items/'
    | '/locations/'
    | '/references/'
    | '/inventory/history/'
    | '/inventory/issue/'
    | '/inventory/receive/'
    | '/inventory/stocktake/'
    | '/receipts/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/$'
    | '/inventory'
    | '/license'
    | '/categories'
    | '/items'
    | '/locations'
    | '/references'
    | '/inventory/history'
    | '/inventory/issue'
    | '/inventory/receive'
    | '/inventory/stocktake'
    | '/receipts/new'
  id:
    | '__root__'
    | '/_app'
    | '/_app/_master'
    | '/api/$'
    | '/_app/'
    | '/_app/inventory/'
    | '/_app/license/'
    | '/_app/_master/categories/'
    | '/_app/_master/items/'
    | '/_app/_master/locations/'
    | '/_app/_master/references/'
    | '/_app/inventory/history/'
    | '/_app/inventory/issue/'
    | '/_app/inventory/receive/'
    | '/_app/inventory/stocktake/'
    | '/_app/receipts/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_master': {
      id: '/_app/_master'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppMasterRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/license/': {
      id: '/_app/license/'
      path: '/license'
      fullPath: '/license/'
      preLoaderRoute: typeof AppLicenseIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_master/categories/': {
      id: '/_app/_master/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof AppMasterCategoriesIndexRouteImport
      parentRoute: typeof AppMasterRoute
    }
    '/_app/_master/items/': {
      id: '/_app/_master/items/'
      path: '/items'
      fullPath: '/items/'
      preLoaderRoute: typeof AppMasterItemsIndexRouteImport
      parentRoute: typeof AppMasterRoute
    }
    '/_app/_master/locations/': {
      id: '/_app/_master/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof AppMasterLocationsIndexRouteImport
      parentRoute: typeof AppMasterRoute
    }
    '/_app/_master/references/': {
      id: '/_app/_master/references/'
      path: '/references'
      fullPath: '/references/'
      preLoaderRoute: typeof AppMasterReferencesIndexRouteImport
      parentRoute: typeof AppMasterRoute
    }
    '/_app/inventory/history/': {
      id: '/_app/inventory/history/'
      path: '/inventory/history'
      fullPath: '/inventory/history/'
      preLoaderRoute: typeof AppInventoryHistoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/issue/': {
      id: '/_app/inventory/issue/'
      path: '/inventory/issue'
      fullPath: '/inventory/issue/'
      preLoaderRoute: typeof AppInventoryIssueIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/receive/': {
      id: '/_app/inventory/receive/'
      path: '/inventory/receive'
      fullPath: '/inventory/receive/'
      preLoaderRoute: typeof AppInventoryReceiveIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/stocktake/': {
      id: '/_app/inventory/stocktake/'
      path: '/inventory/stocktake'
      fullPath: '/inventory/stocktake/'
      preLoaderRoute: typeof AppInventoryStocktakeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receipts/new/': {
      id: '/_app/receipts/new/'
      path: '/receipts/new'
      fullPath: '/receipts/new/'
      preLoaderRoute: typeof AppReceiptsNewIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppMasterRouteChildren {
  AppMasterCategoriesIndexRoute: typeof AppMasterCategoriesIndexRoute
  AppMasterItemsIndexRoute: typeof AppMasterItemsIndexRoute
  AppMasterLocationsIndexRoute: typeof AppMasterLocationsIndexRoute
  AppMasterReferencesIndexRoute: typeof AppMasterReferencesIndexRoute
}

const AppMasterRouteChildren: AppMasterRouteChildren = {
  AppMasterCategoriesIndexRoute: AppMasterCategoriesIndexRoute,
  AppMasterItemsIndexRoute: AppMasterItemsIndexRoute,
  AppMasterLocationsIndexRoute: AppMasterLocationsIndexRoute,
  AppMasterReferencesIndexRoute: AppMasterReferencesIndexRoute,
}

const AppMasterRouteWithChildren = AppMasterRoute._addFileChildren(
  AppMasterRouteChildren,
)

interface AppRouteChildren {
  AppMasterRoute: typeof AppMasterRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
  AppLicenseIndexRoute: typeof AppLicenseIndexRoute
  AppInventoryHistoryIndexRoute: typeof AppInventoryHistoryIndexRoute
  AppInventoryIssueIndexRoute: typeof AppInventoryIssueIndexRoute
  AppInventoryReceiveIndexRoute: typeof AppInventoryReceiveIndexRoute
  AppInventoryStocktakeIndexRoute: typeof AppInventoryStocktakeIndexRoute
  AppReceiptsNewIndexRoute: typeof AppReceiptsNewIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMasterRoute: AppMasterRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
  AppLicenseIndexRoute: AppLicenseIndexRoute,
  AppInventoryHistoryIndexRoute: AppInventoryHistoryIndexRoute,
  AppInventoryIssueIndexRoute: AppInventoryIssueIndexRoute,
  AppInventoryReceiveIndexRoute: AppInventoryReceiveIndexRoute,
  AppInventoryStocktakeIndexRoute: AppInventoryStocktakeIndexRoute,
  AppReceiptsNewIndexRoute: AppReceiptsNewIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
